name: Build and Push Docker Images

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.check-master.outputs.commit }}
      changed: ${{ steps.check-master.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check master branch updates
        id: check-master
        run: |
          LATEST_COMMIT=$(curl -s https://api.github.com/repos/emersion/soju/commits/master | jq -r '.sha')

          if [ -f "last-commit.txt" ]; then
            LAST_COMMIT=$(cat last-commit.txt)
            echo "Last built commit: $LAST_COMMIT"
          else
            LAST_COMMIT=""
            echo "No previous commit found"
          fi
          
          if [ "$LATEST_COMMIT" != "$LAST_COMMIT" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
            echo "Master branch has new commits"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
            echo "No new commits on master branch"
          fi

  build-master:
    needs: check-updates
    if: needs.check-updates.outputs.changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.check-updates.outputs.commit }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SOJU_VERSION=master
            SOJU_COMMIT=${{ needs.check-updates.outputs.commit }}
          platforms: linux/amd64,linux/arm64

      - name: Update commit record
        run: |
          echo "${{ needs.check-updates.outputs.commit }}" > last-commit.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last-commit.txt
          git commit -m "Update commit to ${{ needs.check-updates.outputs.commit }}" || exit 0
          git push
